### PR TITLE
Fixes #15215: fix Openscap technique

### PR DESCRIPTION
**Pull request by el-k0022**
https://issues.rudder.io/issues/15215

### CODE REVIEW

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by peckpeck** [comment]
You need to include the technique source here, you can find it in /var/rudder/configuration-repository/ncf/50_techniques

You also need to list openscap files and where to find them.

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Pull request merged**
