### PR TITLE
Fixes #9590: Move Rudder changelogs into release-data

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/9590

### CODE REVIEW

**Comment by amousset** [comment]
WIP

**Comment by jooooooon** [comment]
Looks like a great start! I've added one of these files as the source for a Wordpress page, see https://www.rudder-project.org/site/release-notes/. It will update when you update your git branch (but I'm not sure what the trigger is, I assume there is some level of caching in Wordpress). I hope this will be useful to see the final result.

**Comment by amousset** [comment]
@jooooooon @peckpeck Ready for review. The is room for improvement in formatting for 4.0+, but I think it is enough for old changelogs.

@jooooooon It seems there is some cache, the content has bot been updated yet.

**Comment by amousset** [comment]
There are some broken links containing unwanted backslashes.

**Comment by jooooooon** [comment]
The result of this looks good, but until we have a new process to generate change logs in this format, is it really a good idea to commit these? What if we release new minor versions on the 3.1/3.2 branch next week, surely this will make these out of date?

**Comment by amousset** [comment]
Generating markdown changelogs with the current changelog generation script is very easy, but we may indeed take some time to migrate the actual changelogs into wordpress.

**Comment by peckpeck** [comment]
Since there is now https://github.com/Normation/packaging/pull/126 we can migrate easily

**Comment by amousset** [comment]
What is still needed before migrating completely is to add all the changelog pages into Wordpress and to change the changelog-x.y pages to these new pages.

**Comment by peckpeck** [comment]
Can wordpress have a single dynamicly generated page or must we create a page for each changelog ?

**Comment by amousset** [comment]
I will have a look but I think we need a page for each file.

**Comment by amousset** [comment]
It does not seem possible with the current setup but I see extensions like (https://wordpress.org/plugins/dynamic-page-content/) that could probably make it possible. It would probably be in conflict with the various cache levels though.

**Comment by peckpeck** [comment]
We only need one per major release, it is fine to not have it if it is complex to implement, just remember that adding thing that cannot be automated is not cool for the release manager

**Comment by amousset** [comment]
Another option that would be completely automated is to generate the changelogs outside of the website, by running some markdown to html tool, but we lose the integration to the website (menu, etc.).

**Comment by amousset** [comment]
Created:

* https://www.rudder-project.org/site/release-notes-4-0/
* https://www.rudder-project.org/site/release-notes-2-10/

As examples. There is a 5 hours cache on the markdown content, and it is possible to manually purge it in the wordpress interface.

**Comment by peckpeck** [comment]
Good, which solution did you choose ?

**Comment by amousset** [comment]
These are manually created pages (and I already had conflict with the caching plugin...).

**Comment by amousset** [comment]
@VinceMacBuche This is the next step to get the changelogs into the website.

**Pull request merged**
