### PR TITLE
Fixes #7894: Write a Rudder cheat sheet

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/7894

### CODE REVIEW

**Comment by amousset** [comment]
* I am unsure where to put it. rudder-doc has branches, and it is probably better to keep cheasheets as version independant as possible.
* It is apparently not easily possible to generate the pdf from cli

**Comment by peckpeck** [comment]
rudder-tools is version independent

**Comment by amousset** [comment]
That's why I put it here for now

**Comment by amousset** [comment]
Commit modified

**Comment by FlorianHeigl** [comment]
Freedom for the cheat sheet! It wants to be released!

**Comment by VinceMacBuche** [comment]
Cheat sheet ! Cheat sheet !

**Pull request merged**
