### PR TITLE
Fixes #15584: publish inventory-hooks

### PR DESCRIPTION
**Pull request by el-k0022**
https://issues.rudder.io/issues/15584

### CODE REVIEW

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by el-k0022** [comment]
Commit modified

**Comment by peckpeck** [comment]
this seems to be a mistake

**Pull request closed without merging**
