### PR TITLE
Fixes #14324: rudder-setup does use same apt file than rudder-agent

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/14324

### CODE REVIEW

**Comment by peckpeck** [comment]
I thought i had already fixed that one

**Comment by peckpeck** [comment]
I can see in rudder-techniques/techniques/applications/aptPackageManagerSettings/3.1/aptPackageManagerSettings.st that the technique uses rudder-apt.list

**Comment by peckpeck** [comment]
you shouldn't have merged this PR, now the agent is incompatible with the apt technique

**Comment by fanf** [comment]
Hum. It seems that not all rudder agent use "rudder.list". In Ubuntu 18 / Rudder 5.0, it's also `rudder-apt.list`. 
So apparently, we changed at some point, and it bricks update. We need to revert that and look at where `rudder.list` is used and migrate that.

**Comment by fanf** [comment]
See https://issues.rudder.io/issues/14334

**Pull request merged**
