### PR TITLE
Fixes #19338: Make a script to help visualize global variables defined in the configuration

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/19338

### CODE REVIEW

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Review by amousset — APPROVED** [review]

**Comment by Fdall** [comment]
PR rebased

**Comment by Fdall** [comment]
PR updated with a new commit

**Pull request merged**
