### PR TITLE
Fixes #15602: Create a script to generate all inventories data

### PR DESCRIPTION
**Pull request by ncharles**
https://issues.rudder.io/issues/15602

### CODE REVIEW

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
PR updated with a new commit

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Comment by amousset** [comment]
OK, squash merging this PR

**Comment by fanf** [comment]
OK, squash merging this PR

**Comment by fanf** [comment]
OK, squash merging this PR

**Comment by fanf** [comment]
Merged by hand

**Pull request closed without merging**
