### PR TITLE
Fixes #11655: Import old ncf-openstack-technique in contrib

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/11655

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Quite impressive ...

**Comment by VinceMacBuche** [comment]
Do you mind if i don't read it completely ? plus no knowledge on openstack ;)

**Comment by amousset** [comment]
You can learn: https://docs.openstack.org/pike/ 📖

**Comment by VinceMacBuche** [comment]
I prefer to have an amousset API

**Pull request merged**
